#!/usr/bin/env bash
# Concatenate modular sources into one file per JS realm.
# Keeps src/ as the editable source of truth; manifest loads dist/.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/dist"
SRC="$ROOT/src"
mkdir -p "$DIST"

bundle() {
  local out="$1"
  shift
  local tmp
  tmp="$(mktemp)"
  {
    echo "/* generated by scripts/bundle.sh — do not edit */"
    echo "(() => {"
    for f in "$@"; do
      local rel="${f#"$ROOT/"}"
      echo ""
      echo "/* ---- ${rel} ---- */"
      echo "try {"
      cat "$f"
      echo "} catch (err) { console.error('[ytad] module failed: ${rel}', err); }"
    done
    echo "})();"
  } >"$tmp"
  mv "$tmp" "$out"
  echo "wrote $out ($(wc -c <"$out") bytes)"
}

bundle "$DIST/main.js" \
  "$SRC/shared/ns.js" \
  "$SRC/shared/constants.js" \
  "$SRC/shared/messaging.js" \
  "$SRC/schema/keys.js" \
  "$SRC/schema/selectors.js" \
  "$SRC/schema/urls.js" \
  "$SRC/schema/dom.js" \
  "$SRC/schema/detect.js" \
  "$SRC/main/sanitize/player.js" \
  "$SRC/main/sanitize/feed.js" \
  "$SRC/main/sanitize/shorts.js" \
  "$SRC/main/sanitize/hooks.js" \
  "$SRC/main/sanitize/bootstrap.js" \
  "$SRC/main/feed-fill/similarity.js" \
  "$SRC/main/feed-fill/meta.js" \
  "$SRC/main/feed-fill/patch.js" \
  "$SRC/main/feed-fill/bootstrap.js"

bundle "$DIST/isolated-bridge.js" \
  "$SRC/shared/ns.js" \
  "$SRC/shared/constants.js" \
  "$SRC/shared/messaging.js" \
  "$SRC/isolated/bridge.js"

bundle "$DIST/isolated-fallback.js" \
  "$SRC/shared/ns.js" \
  "$SRC/shared/constants.js" \
  "$SRC/shared/messaging.js" \
  "$SRC/schema/keys.js" \
  "$SRC/schema/selectors.js" \
  "$SRC/schema/urls.js" \
  "$SRC/schema/dom.js" \
  "$SRC/schema/detect.js" \
  "$SRC/isolated/fallback/bootstrap.js" \
  "$SRC/isolated/sponsor-skip/api.js" \
  "$SRC/isolated/sponsor-skip/notice.js" \
  "$SRC/isolated/sponsor-skip/preview-bar.js" \
  "$SRC/isolated/sponsor-skip/skipper.js" \
  "$SRC/isolated/sponsor-skip/bootstrap.js" \
  "$SRC/isolated/shorts/hide.js" \
  "$SRC/isolated/shorts/redirect.js" \
  "$SRC/isolated/shorts/bootstrap.js" \
  "$SRC/isolated/queue/store.js" \
  "$SRC/isolated/queue/meta.js" \
  "$SRC/isolated/queue/toast.js" \
  "$SRC/isolated/queue/navigate.js" \
  "$SRC/isolated/queue/panel.js" \
  "$SRC/isolated/queue/tiles.js" \
  "$SRC/isolated/queue/native.js" \
  "$SRC/isolated/queue/autoplay.js" \
  "$SRC/isolated/queue/bootstrap.js"

# Background: importScripts paths are relative to the worker file.
# Keep a thin worker in dist that pulls shared modules via importScripts from ../src
# OR bundle shared into the worker. Prefer bundle for one-file reliability.
{
  echo "/* generated by scripts/bundle.sh — do not edit */"
  echo "try {"
  cat "$SRC/shared/ns.js"
  echo "} catch (err) { console.error('[ytad] ns failed', err); }"
  echo "try {"
  cat "$SRC/shared/constants.js"
  echo "} catch (err) { console.error('[ytad] constants failed', err); }"
  echo "try {"
  # Strip importScripts from the original worker body if present
  sed '/^importScripts/d' "$SRC/background/service-worker.js"
  echo "} catch (err) { console.error('[ytad] service worker failed', err); }"
} >"$DIST/service-worker.js"
echo "wrote $DIST/service-worker.js"

{
  cat "$SRC/isolated/fallback/fallback.css"
  echo ""
  cat "$SRC/isolated/sponsor-skip/sponsor-skip.css"
  echo ""
  cat "$SRC/isolated/shorts/shorts.css"
  echo ""
  cat "$SRC/isolated/queue/queue.css"
} >"$DIST/fallback.css"
echo "wrote $DIST/fallback.css"
echo "done."
